name: "Release Browser: Production"

on:
  workflow_dispatch:

run-name: "Release Browser Production"

permissions:
  contents: write
  actions: read

jobs:
  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release-tests'
    uses: ./.github/workflows/_release-browser.yml
    with:
      channel: release
    secrets: inherit
