name: "Release Karton"

on:
  workflow_dispatch:

run-name: "Release Karton"

jobs:
  release:
    # Only run on main or release-tests branch
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release-tests'
    uses: ./.github/workflows/_release-package.yml
    with:
      package: karton
      channel: release
    secrets: inherit
